### ISSUE TITLE
base_convert precision

### ISSUE THREAD

**Issue by kaperys** [m1ome/iso8583#2]
Consider the following hexadecimal bitmap: f23e4491a8e08020

The following binary bitmap is the correct representation of the above hexadecimal one: 11110010 00111110 01000100 10010001 10101000 11100000 10000000 00100000

The following binary bitmap is the outcome of using PHP's base_convert function to represent the above hexadecimal one:  11110010 00111110 01000100 10010001 10101000 11100000 10000000 00000000

Notice how bit 59 is ON in the correct bitmap, and OFF in PHP's.

This is due to PHP's base_convert function losing precision when working with data of a length greater than 32 bits ([see the docs](http://php.net/manual/en/function.base-convert.php)).

I've created a work around in PR #1

**Comment by m1ome** [comment]
Closed by your PR, thank you! 
Awesome job!
